Format scripts through shfmt

diff --git a/gitup b/gitup
--- a/gitup
+++ b/gitup
@@ -14,7 +14,7 @@ declare -a ignore_dirs
 declare -a errs
 
 usage() {
-  LESS=-FEXR less <<'HELP'
+    LESS=-FEXR less <<'HELP'
 gitup [OPTIONS] [dirs]
 
 search for git repos and update them
@@ -34,93 +34,98 @@ HELP
 }
 
 color() {
-  local c
-  c="$1"
-  shift
-  printf '%s' "${colors[$c]}"
-  printf '%s\n' "$@"
-  printf '%s' "${colors[reset]}"
+    local c
+    c="$1"
+    shift
+    printf '%s' "${colors[$c]}"
+    printf '%s\n' "$@"
+    printf '%s' "${colors[reset]}"
 }
 
 err() {
-  color red "$@" >&2
+    color red "$@" >&2
 }
 
 die() {
-  [[ -n "$1" ]] && err "$1"
-  exit 1
+    [[ -n "$1" ]] && err "$1"
+    exit 1
 }
 
 has() {
-  local verbose
-  if [[ $1 = '-v' ]]; then
-    verbose=1
-    shift
-  fi
-  for c; do c="${c%% *}"
-    if ! command -v "$c" &> /dev/null; then
-      (( "$verbose" > 0 )) && err "$c not found"
-      return 1
+    local verbose
+    if [[ $1 == '-v' ]]; then
+        verbose=1
+        shift
     fi
-  done
+    for c; do
+        c="${c%% *}"
+        if ! command -v "$c" &>/dev/null; then
+            (("$verbose" > 0)) && err "$c not found"
+            return 1
+        fi
+    done
 }
 
 has -v fzf git || die
 
-while getopts ':hqp:i:F' x; do o="$OPTARG"
-  case "$x" in
-    h) usage; exit; ;;
+while getopts ':hqp:i:F' x; do
+    o="$OPTARG"
+    case "$x" in
+    h)
+        usage
+        exit
+        ;;
     p) processes="$o" ;;
-    q) (( ++quiet )) ;;
-    i) IFS=',' read -ra ignore_dir <<< "$o" ;;
-    F) (( ++force )) ;;
-  esac
+    q) ((++quiet)) ;;
+    i) IFS=',' read -ra ignore_dir <<<"$o" ;;
+    F) ((++force)) ;;
+    esac
 done
-shift $(( OPTIND - 1 ))
+shift $((OPTIND - 1))
 
 while :; do
-  if [[ -d "$1" ]]; then
-    dirs+=( "$1" )
-  fi
-  shift || break
+    if [[ -d "$1" ]]; then
+        dirs+=("$1")
+    fi
+    shift || break
 done
 
 for o in "${ignore_dir[@]}"; do
-  ignore_dirs+=( -path "*/$o" -o  )
+    ignore_dirs+=(-path "*/$o" -o)
 done
 
-(( ${#dirs[@]} > 0 )) || dirs=("$HOME")
+((${#dirs[@]} > 0)) || dirs=("$HOME")
 
-mapfile -t repos < <(find "${dirs[@]}"  \
-  \( "${ignore_dirs[@]}" \
+mapfile -t repos < <(find "${dirs[@]}" \
+    \( "${ignore_dirs[@]}" \
     -fstype 'devfs' \
     -o -fstype 'devtmpfs' \
     -o -fstype 'proc' \
-  \) -prune -o -name '.git' -printf '%h\n' 2> /dev/null |
-  fzf --multi --cycle --inline-info +s -e ${force:+-f /})
+    \) -prune -o -name '.git' -printf '%h\n' 2>/dev/null |
+    fzf --multi --cycle --inline-info +s -e ${force:+-f /})
 
-(( ${#repos[@]} > 0 )) || exit
+((${#repos[@]} > 0)) || exit
 
 update() {
-  local name dir
-  dir="$1"
-  name="${dir##*/}"
-  (( quiet > 1 )) || color blue ":: updating $name"
-  if git -C "$dir" pull ${quiet:+-q}; then
-    (( quiet > 1 )) || color green ":: updated $name"
-  else
-    errs+=( "$name" )
-  fi
+    local name dir
+    dir="$1"
+    name="${dir##*/}"
+    ((quiet > 1)) || color blue ":: updating $name"
+    if git -C "$dir" pull ${quiet:+-q}; then
+        ((quiet > 1)) || color green ":: updated $name"
+    else
+        errs+=("$name")
+    fi
 }
 
 for d in "${repos[@]}"; do
-  (( count++ >= processes )) && wait -n
-  update "$d" &
+    ((count++ >= processes)) && wait -n
+    update "$d" &
 done
 wait
 
-if (( "${#errs[@]}" > 0 )); then
-  color red 'The following packages failed to update:'
-  color red "  ${errs[*]}"
+if (("${#errs[@]}" > 0)); then
+    color red 'The following packages failed to update:'
+    color red "  ${errs[*]}"
 fi
 color green "updated ${#repos[@]} repos"
diff --git a/goog b/goog
--- a/goog
+++ b/goog
@@ -5,75 +5,80 @@ declare -r c_reset="${esc}[0m"
 declare -r c_red="${esc}[31m"
 
 err() {
-  printf "${c_red}%s${c_reset}\n" "$*" >&2
+    printf "${c_red}%s${c_reset}\n" "$*" >&2
 }
 
 die() {
-  [[ -n "$1" ]] && err "$1"
-  exit 1
+    [[ -n "$1" ]] && err "$1"
+    exit 1
 }
 
 has() {
-  local verbose=0
-  if [[ $1 == '-v' ]]; then
-    verbose=1
-    shift
-  fi
-  for c; do c="${c%% *}"
-    if ! command -v "$c" &> /dev/null; then
-      (( verbose > 0 )) && err "$c not found"
-      return 1
+    local verbose=0
+    if [[ $1 == '-v' ]]; then
+        verbose=1
+        shift
     fi
-  done
+    for c; do
+        c="${c%% *}"
+        if ! command -v "$c" &>/dev/null; then
+            ((verbose > 0)) && err "$c not found"
+            return 1
+        fi
+    done
 }
 
 openurl() {
-  local url="$1"
-  local browser
-  case "$url" in
-    *youtube.com*|*youtu.be*|*vimeo.com*)
-      browser=$(select_from \
-        mpv mplayer2 mplayer) ;;
+    local url="$1"
+    local browser
+    case "$url" in
+    *youtube.com* | *youtu.be* | *vimeo.com*)
+        browser=$(select_from \
+            mpv mplayer2 mplayer)
+        ;;
     *)
-      browser=$(select_from \
-        -c "pgrep -u $USER -i" \
-        firefox chromium-browser chrome)
-      [[ ! $browser ]] && browser='w3m'
-      ;;
-  esac
-  $browser "$url"
+        browser=$(select_from \
+            -c "pgrep -u $USER -i" \
+            firefox chromium-browser chrome)
+        [[ ! $browser ]] && browser='w3m'
+        ;;
+    esac
+    $browser "$url"
 }
 
 # http://stackoverflow.com/a/10660730
 rawurlencode() {
-  local string="$*"
-  local strlen=${#string}
-  local encoded=""
-  for (( pos=0; pos < strlen; pos++ )); do
-    c="${string:$pos:1}"
-    case "$c" in
-      [-_.~a-zA-Z0-9])
-        o="$c" ;;
-      *)
-        printf -v o '%%%02x' "'$c"
-    esac
-    encoded+="${o}"
-  done
-  echo "${encoded}"
+    local string="$*"
+    local strlen=${#string}
+    local encoded=""
+    for ((pos = 0; pos < strlen; pos++)); do
+        c="${string:$pos:1}"
+        case "$c" in
+        [-_.~a-zA-Z0-9])
+            o="$c"
+            ;;
+        *)
+            printf -v o '%%%02x' "'$c"
+            ;;
+        esac
+        encoded+="${o}"
+    done
+    echo "${encoded}"
 }
 
 has -v curl jq fzf || die
 
 if [[ -z "$*" ]]; then
-  die 'nothing to search for'
+    die 'nothing to search for'
 fi
 
-response=$( curl -sfL "http://ajax.googleapis.com/ajax/services/search/web?v=1.0&rsz=8&q=$(rawurlencode "$*")" ) || die 'error connecting to google, check connection'
-json=$( jq -c '.["responseData"]["results"] | map("\(.unescapedUrl) \(.title) | \(.content)") | .[]' <<< "$response" ) || die 'error parsing results :('
-url=$( fzf -e --ansi --cycle --inline-info <\
-  <( sed -r 's/<[^>]*>//g; s/\\n//g; s/^\s*"//; s/",?$//' <<< "$json" ) |
-  cut -d' ' -f1 )
+response=$(curl -sfL "http://ajax.googleapis.com/ajax/services/search/web?v=1.0&rsz=8&q=$(rawurlencode "$*")") || die 'error connecting to google, check connection'
+json=$(jq -c '.["responseData"]["results"] | map("\(.unescapedUrl) \(.title) | \(.content)") | .[]' <<<"$response") || die 'error parsing results :('
+url=$(fzf -e --ansi --cycle --inline-info < <(
+    sed -r 's/<[^>]*>//g; s/\\n//g; s/^\s*"//; s/",?$//' <<<"$json"
+) |
+    cut -d' ' -f1)
 
 if [[ -n "$url" ]]; then
-  openurl "$url"
+    openurl "$url"
 fi
diff --git a/pkgsearch b/pkgsearch
--- a/pkgsearch
+++ b/pkgsearch
@@ -9,7 +9,7 @@ declare distro
 declare preview_pos='right:hidden'
 
 usage() {
-  LESS=-FEXR less <<HELP
+    LESS=-FEXR less <<HELP
 pkgsearch [options] [query]
   lists and installs packages from your distro's repositories
 
@@ -19,79 +19,81 @@ HELP
 }
 
 err() {
-  printf "${c_red}%s${c_reset}\n" "$*" >&2
+    printf "${c_red}%s${c_reset}\n" "$*" >&2
 }
 
 die() {
-  exit 1
+    exit 1
 }
 
 has() {
-  local verbose=0
-  if [[ $1 = '-v' ]]; then
-    verbose=1
-    shift
-  fi
-  for c; do c="${c%% *}"
-    if ! command -v "$c" &> /dev/null; then
-      (( "$verbose" > 0 )) && err "$c not found"
-      return 1
+    local verbose=0
+    if [[ $1 == '-v' ]]; then
+        verbose=1
+        shift
     fi
-  done
+    for c; do
+        c="${c%% *}"
+        if ! command -v "$c" &>/dev/null; then
+            (("$verbose" > 0)) && err "$c not found"
+            return 1
+        fi
+    done
 }
 
 select_from() {
-  local cmd='command -v'
-  for a; do
-    case "$a" in
-      -c)
-        cmd="$2"
-        shift 2
-        ;;
-    esac
-  done
-  for c; do
-    if $cmd "${c%% *}" &> /dev/null; then
-      echo "$c"
-      return 0
-    fi
-  done
-  return 1
+    local cmd='command -v'
+    for a; do
+        case "$a" in
+        -c)
+            cmd="$2"
+            shift 2
+            ;;
+        esac
+    done
+    for c; do
+        if $cmd "${c%% *}" &>/dev/null; then
+            echo "$c"
+            return 0
+        fi
+    done
+    return 1
 }
 
 fzf() {
-  command fzf -e +s --multi --cycle --ansi \
-    --bind='Ctrl-X:toggle-preview' \
-    --no-hscroll --inline-info \
-    --header='tab to select multiple packages, Ctrl-X for more info on a package' "$@"
+    command fzf -e +s --multi --cycle --ansi \
+        --bind='Ctrl-X:toggle-preview' \
+        --no-hscroll --inline-info \
+        --header='tab to select multiple packages, Ctrl-X for more info on a package' "$@"
 }
 
 install() {
-  local pkgs count
-  mapfile -t pkgs
-  (( ${#pkgs} > 0 )) || exit
-  count="${#pkgs[@]} package"
-  (( ${#pkgs[@]} > 1 )) && count+='s'
-  printf "installing %s: %s\n" "$count" "${pkgs[*]}"
-  $1 "${pkgs[@]}" < /dev/tty
+    local pkgs count
+    mapfile -t pkgs
+    ((${#pkgs} > 0)) || exit
+    count="${#pkgs[@]} package"
+    ((${#pkgs[@]} > 1)) && count+='s'
+    printf "installing %s: %s\n" "$count" "${pkgs[*]}"
+    $1 "${pkgs[@]}" </dev/tty
 }
 
 debian() {
-  fzf --preview='apt-cache show {1}' \
-      --query="$1" \
-    < <(apt-cache search '.*' | sort |
-      sed -u -r "s|^([^ ]+)|${c_green}\1${c_reset}|") |
-    cut -d' ' -f1 |
-    install "sudo $(select_from 'apt' 'aptitude' 'apt-get') install"
+    fzf --preview='apt-cache show {1}' \
+        --query="$1" \
+        < <(apt-cache search '.*' | sort |
+            sed -u -r "s|^([^ ]+)|${c_green}\1${c_reset}|") |
+        cut -d' ' -f1 |
+        install "sudo $(select_from 'apt' 'aptitude' 'apt-get') install"
 }
 
 arch() {
-  local search packages
-  search='pacman'
-  [[ -n "$1" ]] && search=$(select_from 'pacaur' 'trizen' 'yaourt' 'packer' 'apacman' 'pacman')
-  packages=$(fzf --preview="$search -Si {2}" \
-    < <( $search -Ss "$1" |
-      gawk '{
+    local search packages
+    search='pacman'
+    [[ -n "$1" ]] && search=$(select_from 'pacaur' 'trizen' 'yaourt' 'packer' 'apacman' 'pacman')
+    packages=$(fzf --preview="$search -Si {2}" \
+        < <(
+            $search -Ss "$1" |
+                gawk '{
         getline descr;
         sub(/ */,"", descr);
         repo = blue "[" gensub(/\/.*/, "", 1) "]" reset;
@@ -99,33 +101,39 @@ arch() {
         info = gensub(/[^ ]* /, "", 1);
         print repo, name, info, descr;
       }' blue="$c_blue" green="$c_green" reset="$c_reset"
-    ) | cut -d' ' -f2)
-  [[ "$search" = "pacman" ]] && search="sudo pacman"
-  install "$search -S" <<< "$packages"
+        ) | cut -d' ' -f2)
+    [[ "$search" == "pacman" ]] && search="sudo pacman"
+    install "$search -S" <<<"$packages"
 }
 
 void() {
-  local package_list packagename='{ sub(/-[^\-]*$/, "", $2); print $2 }'
-  package_list=$(xbps-query -Rs '' | sort)
-  fzf --preview="p=\$(awk \"$packagename\" <<< {}); xbps-query -Rx \$p" \
-      --query="$1" <<< "$package_list" |
-    awk "$packagename" |
-    install 'xbps-install -S'
+    local package_list packagename='{ sub(/-[^\-]*$/, "", $2); print $2 }'
+    package_list=$(xbps-query -Rs '' | sort)
+    fzf --preview="p=\$(awk \"$packagename\" <<< {}); xbps-query -Rx \$p" \
+        --query="$1" <<<"$package_list" |
+        awk "$packagename" |
+        install 'xbps-install -S'
 }
 
 fedora() {
-  fzf --query="$*" --preview='p={}; p="${p%% *}"; dnf -q info "${p%.*}"' \
-    < <(dnf -qC repoquery --qf "${c_green}%{name} ${c_reset} - %{summary}" \*) |
-    awk '{ package=$1; sub(/\.\S+/, "", package); print package }' |
-    install 'sudo dnf install'
+    fzf --query="$*" --preview='p={}; p="${p%% *}"; dnf -q info "${p%.*}"' \
+        < <(dnf -qC repoquery --qf "${c_green}%{name} ${c_reset} - %{summary}" \*) |
+        awk '{ package=$1; sub(/\.\S+/, "", package); print package }' |
+        install 'sudo dnf install'
 }
 
 while true; do
-  case "$1" in
-    -h|--help) usage; exit ;;
-    -p|--preview) preview_pos="$2"; shift 2 ;;
-    *) break
-  esac
+    case "$1" in
+    -h | --help)
+        usage
+        exit
+        ;;
+    -p | --preview)
+        preview_pos="$2"
+        shift 2
+        ;;
+    *) break ;;
+    esac
 done
 
 has -v fzf gawk || die
@@ -133,16 +141,16 @@ has -v fzf gawk || die
 request="$*"
 
 if [[ -r /etc/os-release ]]; then
-  distro=$(awk -F'=' '"NAME" == $1 { gsub("\"", "", $2); print tolower($2); }' /etc/os-release)
-  distro="${distro%% *}"
+    distro=$(awk -F'=' '"NAME" == $1 { gsub("\"", "", $2); print tolower($2); }' /etc/os-release)
+    distro="${distro%% *}"
 fi
 
 case "$distro" in
-  debian|ubuntu) debian "$request" ;;
-  arch) arch "$request" ;;
-  void) void "$request" ;;
-  fedora) fedora "$request" ;;
-  *) die 'unknown distro :(' ;;
+debian | ubuntu) debian "$request" ;;
+arch) arch "$request" ;;
+void) void "$request" ;;
+fedora) fedora "$request" ;;
+*) die 'unknown distro :(' ;;
 esac
 
 # TODO: homebrew: brew desc -s
diff --git a/sshget b/sshget
--- a/sshget
+++ b/sshget
@@ -10,63 +10,64 @@ declare -A paths=()
 declare -a files=()
 
 err() {
-  printf "${c_red}%s${c_reset}\n" "$*" >&2
+    printf "${c_red}%s${c_reset}\n" "$*" >&2
 }
 
 die() {
-  exit 1
+    exit 1
 }
 
 usage() {
-  LESS=-FEXR less <<'HELP'
+    LESS=-FEXR less <<'HELP'
 sshget <user@host1:/path/to/search ...>
 HELP
 }
 
 has() {
-  local verbose=0
-  if [[ $1 = '-v' ]]; then
-    verbose=1
-    shift
-  fi
-  for c; do c="${c%% *}"
-    if ! command -v "$c" &> /dev/null; then
-      (( verbose > 0 )) && err "$c not found"
-      return 1
+    local verbose=0
+    if [[ $1 == '-v' ]]; then
+        verbose=1
+        shift
     fi
-  done
+    for c; do
+        c="${c%% *}"
+        if ! command -v "$c" &>/dev/null; then
+            ((verbose > 0)) && err "$c not found"
+            return 1
+        fi
+    done
 }
 
 has -v fzf rsync || die
 
 cleanup() {
-  [[ -e "$fifo" ]] && rm "$fifo"
+    [[ -e "$fifo" ]] && rm "$fifo"
 }
 trap cleanup SIGHUP SIGINT SIGTERM
 
 mkfifo "$fifo"
 
-if (( $# < 1 )); then
-  usage
-  die
+if (($# < 1)); then
+    usage
+    die
 fi
 
 for a; do
-  host="${a%:*}"
-  path="${a##*:}"
-  domains+=( ["$a"]="$host" )
-  paths+=( ["$a"]="$path" )
-  shift
+    host="${a%:*}"
+    path="${a##*:}"
+    domains+=(["$a"]="$host")
+    paths+=(["$a"]="$path")
+    shift
 done
 
 for s in "${!domains[@]}"; do
-  ssh "${domains[$s]}" "find ${paths[$s]}" | sed -r "s|^|${domains[$s]}:|" >> "$fifo" &
+    ssh "${domains[$s]}" "find ${paths[$s]}" | sed -r "s|^|${domains[$s]}:|" >>"$fifo" &
 done
 
-mapfile -t files < <(fzf -e --inline-info +s --multi --cycle --bind='Ctrl-A:toggle-all,`:jump' < "$fifo")
+mapfile -t files < <(fzf -e --inline-info +s --multi --cycle --bind='Ctrl-A:toggle-all,`:jump' <"$fifo")
 
-if (( ${#files[@]} )); then
-  rsync --protect-args -auvzP -e ssh "${files[@]}" .
+if ((${#files[@]})); then
+    rsync --protect-args -auvzP -e ssh "${files[@]}" .
 fi
 
 cleanup
